const { validationResult, Result } = require('express-validator');
const cashService = require('../services/cashService');
const { DateTime } = require("luxon");

exports.statusCash = async (req, res) => {
  try {
    // Usa a data atual com fuso de Bel√©m
    const date = DateTime.now().setZone("America/Belem").toJSDate();
    const data = await cashService.statusCashService(date);

    if(!data) {
      return res.status(404).json({
        success: false,
        message: 'Nenhum caixa encontrado',
      })
    }

    return res.status(200).json({
      success: true,
      cash: data
    });
  } catch (error) {
    console.error(`[CashController] Erro ao buscar status do caixa: ${error}`);
    res.status(500).json({
      success: false,
      message: "Erro interno ao verificar o status do caixa.",
    });
  }
};

exports.openCash = async (req, res) => {
  const errors = validationResult(req);

  if (!errors.isEmpty()) {
    return res.status(400).json({
      success: false,
      message: 'Dados inv√°lidos. Verifique os campos e tente novamente.',
    });
  }

  const { initialValue } = req.body;
  const user = req.user;
  const date = DateTime.now().setZone("America/Belem")

  try {
    const isOpen = await cashService.openCashService(user, initialValue, date);

    if (!isOpen) {
      return res.status(409).json({
        success: false,
        message: "J√° existe um caixa aberto para hoje.",
      });
    }

    return res.status(201).json({
      success: true,
      cash: isOpen
    });
  } catch (error) {
    console.log(`[CashController] Erro ao abrir caixa: ${error}`);
    return res.status(500).json({
      success: false,
      message: "Erro interno ao tentar abrir o caixa.",
    });
  }
};

exports.closeCash = async (req, res) => {
  const errors = validationResult(req);

  if (!errors.isEmpty()) {
    return res.status(400).json({
      success: false,
      message: 'Dados inv√°lidos. Verifique os campos e tente novamente.',
    });
  }

  const { id } = req.params
  const { finalValue } = req.body
  const date = DateTime.now().setZone("America/Belem")
  try{
    const cash = await cashService.closeCashService(id, finalValue, date);

    if(!cash) {
      return res.status(404).json({
        success: false,
        message: 'Caixa n√£o encontrado',
      })
    }

    return res.status(200).json({
      success: true,
      data: cash,
      message: 'Caixa Fechado com sucesso'
    })
  } catch (error) {
    console.log(`[CashController] Erro ao tentar fechar o caixa: ${error}`);
    return res.status(500).json({
      success: false,
      message: 'Erro interno do servidor'
    })
  }
}

exports.reopenCash = async (req, res) => {
  const errors = validationResult(req);

  if (!errors.isEmpty()) {
    console.warn("‚ùå Erros de valida√ß√£o ao tentar reabrir caixa:", errors.array());
    return res.status(400).json({
      success: false,
      message: 'Dados inv√°lidos. Verifique os campos e tente novamente.',
    });
  }

  const { cashId } = req.params;
  console.log("üì• Requisi√ß√£o para reabrir caixa:", cashId);

  try {
    const result = await cashService.reopenCashService(cashId);

    console.log("‚úÖ Caixa reaberto com sucesso:", result.id);
    return res.status(200).json({
      success: true,
      message: "Caixa reaberto com sucesso.",
      cash: result
    });
  } catch (error) {
    console.error("‚ùå Erro ao reabrir caixa:", error.message);
    return res.status(400).json({
      success: false,
      message: error.message || "Erro ao tentar reabrir o caixa."
    });
  }
};

exports.geralCashData = async (req, res) => {
  const errors = validationResult(req);

  if (!errors.isEmpty()) {
    return res.status(400).json({
      success: false,
      message: 'Dados inv√°lidos. Verifique os campos e tente novamente.',
    });
  }

  const { id } = req.params;
  
  try{
    const data = await cashService.geralCashDataService(id);
    if (!data) {
      return res.status(404).json({
        success: false,
        message: 'Caixa n√£o encontrado'
      })
    }

    const totalValue = Number(data.initial_value) + Number(data.general_sale_total) + Number(data.vehicle_entry_total)
    data.totalValue = totalValue

    return res.status(200).json({
      success: true,
      data: data
    })
  } catch (error) {
    console.log(`[CashController] Erro ao tentar buscar os dados gerais do caixa: ${error}`);
    return res.status(500).json({
      success: false,
      message: 'Erro ao tentar buscar os dados gerais do caixa',
      error: error.message
    })
  }
}

exports.BillingMethod = async (req, res) => {
  try {
    const methods = await cashService.BillingMethodService();

    if(!methods) {
      return res.status(404).json({
        success: false,
        message: 'Nenhuma regra encontrada'
      })
    }

    return res.status(200).json({
      success: true,
      methods: methods
    });
  } catch (error) {
    console.error("Erro na rota de m√©todos de cobran√ßa:", error);
    return res.status(500).json({ 
      success: false,
      message: 'Erro ao buscar m√©todos de cobran√ßa' 
    });
  }
};

exports.cashData = async (req, res) => {
  const errors = validationResult(req);

  if (!errors.isEmpty()) {
    return res.status(400).json({
      success: false,
      message: 'Dados inv√°lidos. Verifique os campos e tente novamente.',
    });
  }

  const { id } = req.params;

  try {
    const cash = await cashService.cashDataService(id);

    if (!cash) {
      return res.status(404).json({
        success: false,
        message: 'Caixa n√£o encontrado ou n√£o est√° aberto.',
      });
    }

    

    console.log(cash)
    return res.status(200).json({
      success: true,
      data: cash
    });
  } catch (error) {
    console.error('Erro ao buscar dados do caixa:', error);
    return res.status(500).json({
      success: false,
      message: 'Erro interno ao buscar dados do caixa.'
    });
  }
}

exports.OutgoingExpense = async (req, res) => {
  const errors = validationResult(req);

  if (!errors.isEmpty()) {
    return res.status(400).json({
      success: false,
      message: 'Dados inv√°lidos. Verifique os campos e tente novamente.',
      errors: errors.array()
    });
  }

  const { id } = req.params;

  try {
    const response = await cashService.OutgoingExpenseService(id);

    // Caixa n√£o encontrado
    if (response === null) {
      return res.status(404).json({
        success: false,
        message: 'Caixa n√£o encontrado.'
      });
    }

    // Caixa existe mas n√£o h√° despesas
    if (response.length === 0) {
      return res.status(200).json({
        success: true,
        message: 'Nenhuma despesa registrada para este caixa.',
        data: []
      });
    }

    // Retorno com sucesso e dados
    return res.status(200).json({
      success: true,
      message: 'Despesas encontradas com sucesso.',
      data: response
    });

  } catch (error) {
    console.error("Erro ao buscar despesas:", error);
    return res.status(500).json({
      success: false,
      message: 'Erro interno ao buscar despesas.',
      error: error.message
    });
  }
};

exports.registerOutgoing = async (req, res) => {
  const errors = validationResult(req);

  if (!errors.isEmpty()) {
    return res.status(400).json({
      success: false,
      message: 'Dados inv√°lidos. Verifique os campos e tente novamente.',
      errors: errors.array()
    });
  }

  const belemDate = DateTime.now().setZone("America/Belem").toJSDate();
  const { description, amount, method, openCashId } = req.body;
  const user = req.user;

  try {
    const result = await cashService.registerOutgoingService(
      description,
      amount,
      method.toUpperCase(),
      openCashId,
      belemDate,
      user
    );

    return res.status(201).json({
      success: true,
      message: 'Despesa registrada com sucesso.',
      data: result
    });

  } catch (error) {
    console.error("Erro ao registrar despesa:", error);
    return res.status(500).json({
      success: false,
      message: 'Erro ao registrar despesa.',
      error: error.message
    });
  }
};